### ISSUE TITLE
Babel uses reserved keyword `default` when compiling

### ISSUE THREAD

**Issue by p6l-richard** [labnol/apps-script-starter#21]
When installing additional npm packages, some of them get transpiled using `.default` to access an object. However, in GAS `default` is a reserved keyword resulting in an error.

## Expected Behavior
Webpack should use Babel to transpile Object property accessing using the bracket notation instead of the dot notation.

## Current Behavior
`clasp push` throws error
```
{
errors: [
    {
      message: 'Syntax error: Missing name after . operator. line: XXX file: bundle.js',
      domain: 'global',
      reason: 'badRequest'
    }
  ]
}
```

bundle.js:
```
//...
Object.defineProperty(exports, "DataFrame", {
  enumerable: true,
  get: function get() {
    return _dataframe.default;
  }
});
//...
```

index.js:
```
import DataFrame from 'dataframe-js';
//...
const response = () => {
  return JSON.parse(UrlFetchApp.fetch(url, { method: 'get' }));
}
DataFrame.fromJSON(response()).then(df => {
  Logger.log(df);
 });
```
## Possible Solution
Beginner friendly explanation for installing additional packages that might conflict with the `default` keyword or include [babel-preset-gas](https://github.com/fossamagna/babel-preset-gas) in your project setup.

## Steps to Reproduce
1. clone `apps-script-starter`
2. cd to project, `npm install dataframe-js`
3. use `dataframe-js` functionality
4. `npm run deploy`

## Context (Environment)
I am a beginner wanting to set up an environment to develop in GAS using JavaScript. Since I'm handling data from APIs to be pushed to a Google Sheet, I would like to work with data frames to make data handling easier.

**Comment by labnol** [comment]
The GAS preset includes the following plugins:

- babel-plugin-transform-member-expression-literals
- babel-plugin-transform-property-literals

These are included in Apps Script Starter already so not sure if it would resolve the issue.

**Comment by p6l-richard** [comment]
@labnol Got it. 
One could also simply avoid certain packages who will use the reserved keyword (however I'm unsure how to identify them).
Any idea comes to mind?

**Comment by labnol** [comment]
@p6l-richard - I've updated the Apps Script Starter kit to use the new v8 Runtime that should resolve this issue.  Please check.

**Comment by p6l-richard** [comment]
For this particular issue it still doesn't work as the file becomes too big (>2MB file size). Apparently [facebook business SDK](https://github.com/facebook/facebook-nodejs-business-sdk) is too heavy when bundled (even though in your settings the minimizer is enabled).
